"""
faiss_retriever.py
──────────────────
Semantic retrieval module — runs multi-query FAISS search, merges results,
deduplicates, and returns the top-N metadata dicts.

The retriever:
    1. Accepts multiple query strings (generated by the mood extractor).
    2. Embeds each query with embed_query.py.
    3. Searches the pre-built FAISS index for each query.
    4. Merges all hits, removes duplicates, and re-ranks by score.
    5. Optionally filters out titles already shown in the session.

Classes:
    FAISSRetriever — manages index loading and multi-query search.
"""

import json
import logging
from functools import cached_property
from pathlib import Path
from typing import Any

import faiss
import numpy as np

from backend.config import FAISS_INDEX_PATH, METADATA_STORE_PATH, TOP_K_RESULTS
from backend.rag.embed_query import embed_queries

logger = logging.getLogger(__name__)


class FAISSRetriever:
    """
    Loads the FAISS index and metadata store, then performs multi-query
    semantic search over the pre-built vector database.

    The index is loaded lazily on first search call and cached for the
    process lifetime.

    Args:
        top_k (int): Number of candidates to retrieve per query.
    """

    def __init__(self, top_k: int = TOP_K_RESULTS) -> None:
        """
        Initialise the retriever.

        Args:
            top_k (int): Results per query before merging. Defaults to config.
        """
        self._top_k = top_k

    # ── Lazy index and metadata loading ──────────────────────────────────────

    @cached_property
    def _index(self) -> faiss.Index:
        """
        Load the FAISS index from disk (once per process).

        Returns:
            faiss.Index: The loaded vector index.

        Raises:
            FileNotFoundError: If the index file does not exist.
        """
        path = Path(FAISS_INDEX_PATH)
        if not path.exists():
            raise FileNotFoundError(
                f"FAISS index not found at {path}. "
                "Run embed_builder.py to generate it."
            )
        logger.info("Loading FAISS index from %s…", path)
        index = faiss.read_index(str(path))
        logger.info("FAISS index loaded: %d vectors", index.ntotal)
        return index

    @cached_property
    def _metadata(self) -> list[dict[str, Any]]:
        """
        Load the metadata store from disk (once per process).

        Returns:
            list[dict[str, Any]]: One dict per vector, same order as index.

        Raises:
            FileNotFoundError: If metadata_store.json does not exist.
        """
        path = Path(METADATA_STORE_PATH)
        if not path.exists():
            raise FileNotFoundError(
                f"Metadata store not found at {path}. "
                "Run embed_builder.py to generate it."
            )
        logger.info("Loading metadata store from %s…", path)
        return json.loads(path.read_text(encoding="utf-8"))

    # ── Search ────────────────────────────────────────────────────────────────

    def search(
        self,
        queries: list[str],
        excluded_titles: list[str] | None = None,
        top_n: int | None = None,
    ) -> list[dict[str, Any]]:
        """
        Multi-query semantic search — embeds each query, searches FAISS,
        merges and deduplicates hits.

        Args:
            queries         (list[str]): 1-3 semantic search queries.
            excluded_titles (list[str] | None): Titles to exclude (already shown).
            top_n           (int | None): Final number of results to return.
                                          Defaults to TOP_K_RESULTS.

        Returns:
            list[dict[str, Any]]: Merged, ranked, deduplicated metadata records.
        """
        if not queries:
            logger.warning("No queries provided to FAISSRetriever.search()")
            return []

        excluded = {t.lower() for t in (excluded_titles or [])}
        target_n = top_n or self._top_k

        # ── Embed all queries at once ─────────────────────────────────────────
        query_vectors = embed_queries(queries)   # shape: (n_queries, dim)

        # ── FAISS batch search ────────────────────────────────────────────────
        scores_matrix, idx_matrix = self._index.search(
            query_vectors, self._top_k
        )  # shapes: (n_queries, top_k)

        # ── Merge and deduplicate ─────────────────────────────────────────────
        seen_indices: set[int] = set()
        candidates: list[tuple[float, int]] = []   # (score, vector_index)

        for q_scores, q_indices in zip(scores_matrix, idx_matrix):
            for score, idx in zip(q_scores, q_indices):
                if idx == -1 or idx in seen_indices:
                    continue
                seen_indices.add(idx)
                candidates.append((float(score), int(idx)))

        # ── Sort by score descending ──────────────────────────────────────────
        candidates.sort(key=lambda x: x[0], reverse=True)

        # ── Resolve metadata and apply exclusion filter ───────────────────────
        results: list[dict[str, Any]] = []
        for _score, idx in candidates:
            if idx >= len(self._metadata):
                continue
            record = self._metadata[idx].copy()
            title_lower = record.get("title", "").lower()

            if title_lower in excluded:
                continue

            record["_retrieval_score"] = round(_score, 4)
            results.append(record)

            if len(results) >= target_n:
                break

        logger.info(
            "FAISSRetriever returned %d results for %d queries",
            len(results), len(queries)
        )
        return results

    def search_broad(
        self,
        fallback_queries: list[str] | None = None,
        excluded_titles: list[str] | None = None,
    ) -> list[dict[str, Any]]:
        """
        Broad fallback search using generic feel-good queries.

        Called by the pipeline when the primary retrieval yields weak results.

        Args:
            fallback_queries (list[str] | None): Override default broad queries.
            excluded_titles  (list[str] | None): Titles to exclude.

        Returns:
            list[dict[str, Any]]: Broader set of results.
        """
        queries = fallback_queries or [
            "popular entertaining movies and shows",
            "critically acclaimed feel-good films",
            "best movies to watch right now",
        ]
        logger.info("Running broad fallback search…")
        return self.search(queries, excluded_titles=excluded_titles, top_n=TOP_K_RESULTS)
